# Generated by Django 4.2 on 2023-04-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cc', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('birthDay', models.DateField()),
                ('photo', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
    ]
