# Generated by Django 4.2.1 on 2023-05-08 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cc', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='CC')),
                ('fullname', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=16)),
                ('birthday', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Binnacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nit', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='NIT')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('objective', models.TextField()),
                ('results', models.TextField()),
                ('reach', models.TextField()),
                ('state', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ownerCompany', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('date', models.DateField()),
                ('binnacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.binnacle')),
            ],
        ),
        migrations.AddField(
            model_name='binnacle',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.company'),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.project'),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.quotation'),
        ),
    ]
