# Generated by Django 4.2 on 2023-04-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binnacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nit', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='NIT')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('cc', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='CC')),
                ('fullname', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('results', models.TextField()),
                ('reach', models.TextField()),
                ('state', models.TextField()),
                ('ownerCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('date', models.DateField()),
                ('binnacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.binnacle')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.user'),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user'),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.company'),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.project'),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.quotation'),
        ),
    ]
