# Generated by Django 4.2 on 2023-04-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='cc',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='CC'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nit', models.BigAutoField(primary_key=True, serialize=False, verbose_name='NIT')),
                ('phoneNumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('user_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.users')),
            ],
        ),
    ]
