# Generated by Django 4.2.1 on 2023-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rename_phonenumber_company_phonenumberc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='hour',
            field=models.TimeField(default='8:00'),
            preserve_default=False,
        ),
    ]
