# Generated by Django 4.2 on 2023-04-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_binnacle_quotation_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binnacle',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.quotation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user'),
        ),
    ]
