# Generated by Django 4.2 on 2023-04-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_remove_users_id_alter_users_cc_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('idProject', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('results', models.TextField()),
                ('reach', models.TextField()),
                ('state', models.TextField()),
                ('company_nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.company')),
            ],
        ),
    ]
