# Generated by Django 4.2 on 2023-04-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_binnacle_quotation_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binnacle',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.quotation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ownerCompany',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.company'),
        ),
    ]
