# Generated by Django 4.2 on 2023-04-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_binnacle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('binnacleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.binnacle')),
                ('user_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.users')),
            ],
        ),
    ]
