# Generated by Django 4.2.1 on 2023-05-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_company_photo_project_name_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='photo',
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
