# Generated by Django 4.2 on 2023-04-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.role')),
                ('user_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.users')),
            ],
        ),
    ]
